spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dbpro.accelerator.wtf:10034/ccs
    username: root
    password: LMS++dev
    # 连接池lifetime
    hikari:
      maxlifetime: 400000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumpoolsize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

  # 限制上传文件大小
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  #全局设置JSON传参
  jackson:
    date-format: "yyyy-MM-dd"
    timezone: "GMT+8"


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Cishenn.ccs.entity
  configuration:
    map-underscore-to-camel-case: true
#配置Tomcat
server:
  tomcat:
    max-swallow-size: -1
  port: 8080
  servlet:
    context-path: "/ccs"

aliyun:
  oss:
    endpoint-domain: oss-cn-hangzhou.aliyuncs.com
    bucket: customer-service-backend
    access-key:
      id: LTAI4GAYUYwiT5qKu2fxz7AQ
      secret: qpRKbT0Iy10oQKdfDolSREFXi5Ca5p
